### ISSUE TITLE
Step by step guide to producing chapter files and .svg files

### ISSUE THREAD

**Issue by cmhughes** [openmathdocs/precalc#14]
I'd like to be able to create the OMD chapter `.tex` files; how do I use MBX to do so? I'd also like to create LaTeX svg files, perhaps a pointer to MBX script documentation?

**Comment by Alex-Jordan** [comment]
For the second question, run `mbx -h` and you can see how `mbx` is supposed
to work. As we have discovered, it does not always work with relative file
paths, so when you get to declaring where the final destination of the
output should be, and where the input xml is, it helps to give full file
paths for now (until we make `mbx` more robust.) I run `mbx` by going into
`mathbook`'s main folder, and if I wanted `.tex` files for the
`latex-image-code` elements for say the sample-article, I'd use:

```
./script/mbx -c latex-image -f latex -d
/Users/alexjordan/mathbook/examples/images/
/Users/alexjordan/mathbook/examples/sample-article.xml
```


For the first question, I have a suggestion but I'm not sure I have
convinced you yet. If I can distract you from `precalc` for 30 minutes or
so, I *may* win you over.

   - Clone `scla` from Rob's github, and poke around in its `src` and `xsl`
   folders.
   - In `src`, the "hubfile" is `scla.xml`, which is pretty bare as you can
   see, and mostly just xsl:includes chapter files.
   - Take a look in one of the chapter `xml` files, which are also pretty
   bare. They just xsl:include sections.
   - Open a section xml file, and you will see the content.
   - Back out to the `xsl` folder, and take a look at `scla-html.xsl` and
   `xsl-latex.xsl`. These are thin layers of `xsl` between this project and
   `mathbook`. They have a pointer to where Rob keeps his `mathbook`, which
   you will need to edit to full paths to where you keep yours.
   - Go back to `scla/src` and run
      - `xsltproc -xinclude ../xsl/scla-html.xsl scla.xml`
      - `xsltproc -xinclude --stringparam "latex.font.size" "12pt"
      --stringparam "latex.geometry" "letterpaper,total={6.25in,9.0in}"
      ../xsl/scla-latex.xsl scla.xml >> latexscla.tex`

The first leaves you with many html files. Open any one of them in a
browser to explore the book. The second leaves you with one giant `.tex`
file. Which raises the question, do we need individual `.tex` files for
each chapter? Compartmentalization already takes place among the `.xml`
files. To "include only", it's slightly less convenient, but you can
comment out unwanted parts from `scla.xml`. Perhaps the -xinclude switch
has an "include only" option, which would be perfect.

This leaves one thing more to do: you'll need to run mbx to extract a
latex-image that I put in scla in the Linear Recurrence Relations.

But what about all of our complicated preamble from `precalc`? I just
haven't had time to experiment, but I think passing `--stringparam
"latex.preamble.early" mainfile-early.tex` and `--stringparam
"latex.preamble.late" mainfile-late.tex` will do the trick, where
`mainfile-early.tex` and `mainfile-late.tex` are files we build from
`mainfile.tex`.

I took this as the model to start making the calculus lab manual, and I
like how it's going. I'm 100% sure that we could make `precalc` this way,
and I'm 90% sure that we could get all of our features into the hard copy.
We may have to occasionally add templates to `mathbook`, like say an
`<exploration>` element. That's thin kind of thing that would probably go
into `omd/dev`, and not `origin/dev`.


On Sat, Mar 7, 2015 at 1:11 AM, cmhughes <notifications@github.com> wrote:

> I'd like to be able to create the OMD chapter .tex files; how do I use
> MBX to do so? I'd also like to create LaTeX svg files, perhaps a pointer to
> MBX script documentation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmathdocs/precalc/issues/14>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
For the second question, run `mbx -h` and you can see how `mbx` is supposed
to work. As we have discovered, it does not always work with relative file
paths, so when you get to declaring where the final destination of the
output should be, and where the input xml is, it helps to give full file
paths for now (until we make `mbx` more robust.) I run `mbx` by going into
`mathbook`'s main folder, and if I wanted `.tex` files for the
`latex-image-code` elements for say the sample-article, I'd use:

`
./script/mbx -c latex-image -f latex -d
/Users/alexjordan/mathbook/examples/images/
/Users/alexjordan/mathbook/examples/sample-article.xml
`

For the first question, I have a suggestion but I'm not sure I have
convinced you yet. If I can distract you from `precalc` for 30 minutes or
so, I _may_ win you over.
- Clone `scla` from Rob's github, and poke around in its `src` and `xsl`
  folders.
- In `src`, the "hubfile" is `scla.xml`, which is pretty bare as you can
  see, and mostly just xsl:includes chapter files.
- Take a look in one of the chapter `xml` files, which are also pretty
  bare. They just xsl:include sections.
- Open a section xml file, and you will see the content.
- Back out to the `xsl` folder, and take a look at `scla-html.xsl` and
  `xsl-latex.xsl`. These are thin layers of `xsl` between this project and
  `mathbook`. They have a pointer to where Rob keeps his `mathbook`, which
  you will need to edit to full paths to where you keep yours.
- Go back to `scla/src` and run
  - `xsltproc -xinclude ../xsl/scla-html.xsl scla.xml`
  - `xsltproc -xinclude --stringparam "latex.font.size" "12pt"
    --stringparam "latex.geometry" "letterpaper,total={6.25in,9.0in}"
    ../xsl/scla-latex.xsl scla.xml >> latexscla.tex`

The first leaves you with many html files. Open any one of them in a
browser to explore the book. The second leaves you with one giant `.tex`
file. Which raises the question, do we need individual `.tex` files for
each chapter? Compartmentalization already takes place among the `.xml`
files. To "include only", it's slightly less convenient, but you can
comment out unwanted parts from `scla.xml`. Perhaps the `-xinclude` switch
has an "include only" option, which would be perfect.

This leaves one thing more to do: you'll need to run mbx to extract a
latex-image that I put in scla in the Linear Recurrence Relations.

But what about all of our complicated preamble from `precalc`? I just
haven't had time to experiment, but I think passing `--stringparam
"latex.preamble.early" mainfile-early.tex` and `--stringparam
"latex.preamble.late" mainfile-late.tex` will do the trick, where
`mainfile-early.tex` and `mainfile-late.tex` are files we build from
`mainfile.tex`.

I took this as the model to start making the calculus lab manual, and I
like how it's going. I'm 100% sure that we could make `precalc` this way,
and I'm 90% sure that we could get all of our features into the hard copy.
We may have to occasionally add templates to `mathbook`, like say an
`<exploration>` element. That's thin kind of thing that would probably go
into `omd/dev`, and not `origin/dev`.

**Comment by Alex-Jordan** [comment]
And notably, we may have to edit how `omd/dev` handles `<exercise>` elements. Of course the beauty here is that we can code away with our source, and rejigger the `xsl` later.

**Comment by cmhughes** [comment]
Ok, I'll take a look at this.

> The second leaves you with one giant .tex
> file. Which raises the question, do we need individual .tex files for
> each chapter?

I would still say yes, 100%. `includeonly` allows easy per-chapter chunks to be compiled, allowing cross references to work accurately, and allowing us to produce chapter-chunked pdf files. 

I'd like a translation file that outputs only the chapter content--I'd like to leave `mainfile.tex` out of the `xsl` routine, at least for the immediate future. I'll look at the workflow you've outlined above.

**Comment by Alex-Jordan** [comment]
Clearly `mathbook-html.xsl` cuts up source into separate html files. And it does this in a way that really has nothing to do with how the source is cut up. It just makes new files when there is a new `<chapter>` or new `<section>`. So, surely this could be emulated for `mathbook-latex`. Perhaps a `stringparam` could control whether or not one big latex file is produced, or several smaller ones with `\include` used. If this is worth pursuing, a pull request to origin might be appreciated.

> I would still say yes, 100%. includeonly allows easy per-chapter chunks to be compiled, allowing cross references to work accurately, and allowing us to produce chapter-chunked pdf files. '

When you run `mathbook-html` on your source, `xsltproc` compiles it very fast (the whole thing, not just some chapters). Viewing the html output in a web browser is not quite so fast, since some javascript and css needs to be loaded from afar. But it is still, all told, faster than a typical `pdflatex` compilation. And I think it is on par with a `pdflatex` compilation where `\includeonly` was used in draft mode. If the paradigm changes to focusing on html first for revising, and worrying about the pdf output at the end, I think that concerns about separate tex files for each chapter may become moot. 

I'll prioritize setting up precalc this way in a separate branch, and see if I can get the workflow to be nice while keeping our preamble in place for pdfs. If I get that far, I think that for further content addition, I'll be content to monitor the html output instead of the pdf. I'll ping you and you can check out the branch to see what you think.

**Comment by cmhughes** [comment]
Here is my workflow:
- `xsltproc -xinclude ../xsl/precalc-latex.xsl mainfile.xml` produces chapter `.tex` files
- `xsltproc -xinclude ../xsl/precalc-html.xsl precalc.xml` produces HTML files
- `mbx -vv -c latex-image -f svg -d /home/cmhughes/Documents/projects/openmathdocs/precalc/src/images/ /home/cmhughes/Documents/projects/openmathdocs/precalc/src/precalc
  ` produces the svgs for the HTML
